# Site
repository: sproogen/resume-theme
favicon: images/favicon_2023.ico

# Content configuration version
version: 2

# Personal info
name: Carlos Felipe Navarro Clavería
title: Ph.D. and Electrical Civil Engineer
email: carlosnavarroc@uchile.cl
website: 

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: carlosfnavarroc
github_username:  carlosnavarroc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: carlosnavarroc
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: CarlosNavarroClaveria
# googleplus_username: +jekyll
orcid_username: 0000-0001-9140-9095

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_2023.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there, my name is Carlos, and I'm a PhD and Electrical Civil Engineer interested in Image Processing, Pattern Recognition, and Teaching. My career has been developed around projects that involve high technology and innovation in automation systems in medicine, mining, and retail. My PhD thesis focused on detecting complex patterns using color and texture features.
content:
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  Faculty of Medicine. University of Chile. 
        #link: https://scian.cl/scientific-image-analysis/scian-beta/
        additional_links: 
        # link_text: boringcompany.com
        sub_title:   Postdoctoral Researcher at SCIANLab and Neurosystems
        caption: September 2019 - Present
        quote: >
          Solve problems related to medicine and biology by using automation tools 
        description: | # this will include new lines to allow paragraphs

          Research In [SCIANLab](https://scian.cl/scientific-image-analysis/team-members-scianlab/): 
          
          - RaViTT: Random Vision Transformer Tokens. [FONDECYT grants 1221696](https://arxiv.org/pdf/2306.10959.pdf)
          
          - Massive data processing, the fusion of multi-view microscopy captures of embryos for visualization and quantification. PIA Ring ACT192015.

          - [VolumePeeler: a novel FIJI plugin for geometric tissue peeling to improve visualization and quantification of 3D image stacks.](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-023-05403-z)
          
          - An audiological test detects early the presence of cognitive impairment in older adults. [Fondef project ID20I10371.](https://www.biorxiv.org/content/biorxiv/early/2023/02/05/2023.02.03.527051.full.pdf)
          
          - Segmentation algorithms based on Deep learning to analyze biomedical images in 3D. Fondecyt project initiation 11170475 Stage 2019. [Second place in Segmentation accuracy in Cell Tracking Challenge](http://celltrackingchallenge.net/participants/UCH-CL/). Paper: [3D Nuclei Segmentation through Deep Learning](https://www.computer.org/csdl/proceedings-article/cai/2023/398400a309/1PhCElOJQcM)
          
          - [Automation of the Echocardiography analysis of a murine model using Digital Image Processing and Deep Learning](https://www.cec.uchile.cl/~canavarr/Posters/2022_Automatizacion_Ecocardiografia.pdf). [IV Jornadas de Investigación. Hospital Clínico Universidad de Chile](https://www.redclinica.cl/Portals/0/Users/014/14/14/2485.pdf) 
          
          Research In [Neurosystems](https://neurosistemas.cl/en/2021/10/19/carlos-navarro/):
          
          - Spectral analysis of EEG signals to determine postoperative diseases. Fondef Project ID19I10345. Fondef Project IT21I0041
          
          - Remifentanil enhances propofol hypnotic clinical and electroencephalographic effects in humans during loss of consciousness. [Fondef Project ID19I10345.](https://www.cec.uchile.cl/~canavarr/Posters/2021_Remifentanil_enhances.pdf) 
          
         
      
      - layout: left
        title:  University of Chile - <br> U. Santo Tomás - <br>  U. Andrés Bello
        # link: https://scian.cl/scientific-image-analysis/scian-beta/
        # link_text: boringcompany.com
        sub_title:   Professor
        caption: 2015 - Present
        quote: >
          One of my great passions is teaching. Since my mother and father are teachers, getting other human beings to participate in their learning actively is challenging. 
        description: | # this will include new lines to allow paragraphs
          During these years, I have taught several courses, from fundamental mathematics and physics to those related to my electrical engineering expertise, such as [image processing](https://tinyurl.com/Clases-CNC-Imagenes) or [related laboratories](https://www.die.cl/academicos-jornada-parcial/).
              
      - layout: left
        title:  Faculty of Physical Sciences and Mathematics. University of Chile.
        # link: https://scian.cl/scientific-image-analysis/scian-beta/
        # link_text: boringcompany.com
        sub_title:   Research Assistant
        caption: 2009 - 2018
        quote: >
          In my first experiences, I worked on projects related to automation and image processing in retail and mining, even visiting Teck Highland Valley Copper Mine in Kamloops, Canada, to supervise an installation
        description: | # this will include new lines to allow paragraphs
          INNOVA Project 13IDL2-23589; Optimization of registration algorithms, calculation of descriptor and color models for supermarket products to detect stock breakages. 
          
          Fondef D08I-1060 Pattern recognition by video: surveillance and [mining](https://www.cec.uchile.cl/~canavarr/Posters/2013_Lithological_Gabor.pdf) [applications](https://www.cec.uchile.cl/~canavarr/Posters/2012_Rock_Estimation.pdf).
          
          Electrical Engineer Researcher for the P3 program "Intelligent Systems for Mining" (CSIRO Chile Research Foundation). • Design and construct control, power, and telemetry systems for laboratory and field tests of a Bluetooth-based sensor system for slope stability. (CSIRO Chile Research Foundation)
          
          
      

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Faculty of Physical Sciences and Mathematics. University of Chile.
        caption: 2020
        sub_title: PhD in Electrical Engineering 
        quote: > 
          Thesis: Color–Texture Pattern Classification Using Global–Local Feature Extraction, an SVM Classifier, with Bagging Ensemble Post-Processing
        description: | # this will include new lines to allow paragraphs
          This research provides a new way to attack the classification problem using color and texture and evidence about the importance of using different scales when obtaining the features, to integrate the color and texture information. The results of this investigation led to two publications: a [conference article](https://doi.org/10.1109/SMC.2013.562) and a [magazine article](https://doi.org/10.3390/app9153130).
          [Link Thesis](https://www.cec.uchile.cl/~canavarr/Tesis/Navarro_2020.pdf)

      - layout: left
        title: Faculty of Medicine. University of Chile. 
        caption: 2019
        sub_title: Diploma of Technology in Electrophysiology
        quote: > 
          A first approach to the world of biology and medicine, from an engineering point of view.
          
        description: | # this will include new lines to allow paragraphs
          Processing of bioelectric signals and Electrophysiology of Sensory Systems. Final Work: Theoretical analysis of an electrophysiological signal for clinical use and proposal for clinical application.

      - layout: left
        title: Faculty of Physical Sciences and Mathematics. University of Chile.
        caption: 2010
        sub_title: PhD in Electrical Engineering 
        quote: > 
          Thesis: Molds design for iris detection through Particle Swarm Optimization
        description: | # this will include new lines to allow paragraphs
          Two methodologies were proposed to create templates for iris localization: one made by hand and the other generated by PSO.
          The PSO methodology uses templates that are not based on anthropometric information but instead automatically capture the main features of the eye and allow a better localization of the iris.
          [Link Thesis](https://www.cec.uchile.cl/~canavarr/Tesis/Navarro_2010.pdf)
          
  - title: Thesis Committe member or advisor # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Faculty of Physical Sciences and Mathematics. University of Chile.
        caption: 2023
        sub_title: Thesis in Electrical Engineering 
        description: | # this will include new lines to allow paragraphs
          As advisor:
          * Thesis: <i>Transformer-type neural networks as a tool for classifying HER2 protein overexpression in gastric cancer biopsy images.</i> Author: Diego Muñoz. This study focuses on enhancing gastric cancer diagnosis accuracy through the use of transformer-type neural networks compared to convolutional networks. The transformer model demonstrates superior performance over the CNN, achieving higher accuracy and f1-score in classifying all classes of HER2 protein overexpression. [Link Thesis]()          
          
          As committe member:
          
          * Thesis: <i>Development of an intelligent image recognition engine for last-mile dispatch test photos.</i> Author: Franco Mirauda. In this work, an intelligent image recognition engine is proposed, which allows evaluation of the quality of last-mile dispatches through the review of certain elements in the photograph taken at the moment of product delivery. [Link Thesis](https://repositorio.uchile.cl/bitstream/handle/2250/192990/Desarrollo-de-un-motor-de-reconocimiento-de-imagenes-inteligente-para-fotos-de-pruebas-de-despacho-en-ultima-milla.pdf?sequence=1&isAllowed=y)          
          
          * Thesis: <i>Detection and estimation of portion for granular ingredients.</i> Author: Gonzalo Hernández. This study aims to detect and estimate the portion of granular ingredients in PizzaHut kitchen images using different models, including Yolov6, Faster R-CNN, SAM, MIM, and BinsFormers. [Link Thesis]()

  - title: Other Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Virtual Beauchef
        link: https://tinyurl.com/beauchefvirtual
        # link_text: Project Website
        additional_links:
          - title:  UChile News
            icon: fab fa-github
            url: https://uchile.cl/i176928
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The Beauchef campus was recreated in Gather Town
        description: | # this will include new lines to allow paragraphs
          I started this project using the Gather Town application. This platform encourages social interactions, allowing socialization, and collaborative work in a fun way, creating new digital experiences to bring the University closer to students who have not been able to visit it as a result of the pandemic.
      
      - layout: top-middle
        title: La Ciudad de Los Cesares Producer
        link: https://tinyurl.com/CNC-IMDB
        # link_text: Project Website
        additional_links:
          - title:  La Ciudad de Los Cesares. 
            icon: fab fa-github
            url: http://www.laciudaddeloscesares.cl/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This movie was financed entirely through crowdfunding.          
        description: | # this will include new lines to allow paragraphs
          As a producer of an independent film, my role was coordinating people and objects to follow the work plan as planned. Seeing the final product as a quality product was highly challenging and rewarding.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in engineering some of my other interests and hobbies are:
      - [Photography](https://tinyurl.com/CNC-Fotografia)
      - [Cook](https://www.caldostrong.com/search/label/cocinando-con-caldo)
      - [Astronomy](https://www.caldostrong.com/search/label/astronomia)

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
